
@startuml Administrateur

left to right direction

actor "Administrateur" as Administrateur

rectangle ExpressFood {
  usecase "Créer un compte super admin" as UC1
  usecase "Se connecter" as UC2
  usecase "Maintenance préventive" as UC3
  usecase "Réparer les bugs" as UC4
  usecase "Mise à jour de l'application" as UC5
  usecase "Gestion des utilisateurs" as UC6
}

Administrateur --> UC1
Administrateur --> UC2
Administrateur --> UC3
Administrateur --> UC4
Administrateur --> UC5
Administrateur --> UC6

@enduml
