
@startuml Administrator
left to right direction
actor "Administrator" as fc
rectangle ExpressFood {
  usecase "Preventive maintenance" as UC1
  usecase "Fix the bugs" as UC2
  usecase "Update" as UC3
}
fc --> UC1
fc --> UC2
fc --> UC3
@enduml
