
@startuml Client

left to right direction

actor "Client" as Client #Plum

rectangle ExpressFood {
  usecase "S'inscrire" as UC1
  usecase "Se connecter" as UC2
  usecase "S'informer sur les repas" as UC3
  usecase "Etre informer de la disponibilité des plats" as UC4
  usecase "Passer une commande" as UC5
  usecase "Payer sa commande" as UC6
  usecase "Suivre sa commande" as UC7
}

Client --> UC1
Client --> UC2
Client --> UC3
Client --> UC4
Client --> UC5
Client --> UC6
Client --> UC7

@enduml
