
@startuml EquipeExpFood

left to right direction

actor "EquipeExpFood" as EquipeExpFood

rectangle ExpressFood {
  usecase "Créer un compte admin" as UC1
  usecase "Se connecter" as UC2
  usecase "Créer un compte livreur" as UC3
  usecase "Ajouter des plats salé" as UC4
  usecase "Ajouter des desserts" as UC5
  usecase "Vérifier le stock" as UC6
  usecase "Afficher la liste des commandes du jour" as UC7
}

EquipeExpFood --> UC1
EquipeExpFood --> UC2
EquipeExpFood --> UC3
EquipeExpFood --> UC4
EquipeExpFood --> UC5
EquipeExpFood --> UC6
EquipeExpFood --> UC7



@enduml
