
@startuml Livreur

left to right direction

actor "Livreur" as Livreur

rectangle ExpressFood {
  usecase "Se connecter" as UC1
  usecase "Notifier sa disponibilité" as UC2
  usecase "Informer du stock disponible" as UC3
  usecase "Prendre en charge la livraison" as UC4
  usecase "Livrer la commande" as UC5
}

Livreur --> UC1
Livreur --> UC2
Livreur --> UC3
Livreur --> UC4
Livreur --> UC5

@enduml
