@startuml ExpressFoodSequences

actor actor as Customer #Green
database database as ExpressFood #Blue

Customer  -> ExpressFood: Authentication Request
ExpressFood -> Customer: Authentication Response

Customer  -> ExpressFood: Search  Meal Request
Customer  -> ExpressFood: Search  Meal Response

@enduml