@startuml ClientSequence

skinparam responseMessageBelowArrow true
skinparam SequenceMessageAlignment center

actor Livreur as Livreur #GreenYellow

entity Commande as Commande #LightYellow

actor Client as Client #Plum

database ExpressFood as ExpressFood #HotPink

Livreur -> ExpressFood: demander authentification
alt successful case
ExpressFood -> Livreur: valider authentification 

Livreur -> Livreur: vérifier disponibilité
Livreur -> Commande: prendre en charge la commande

Livreur --> Temps:livrer - 20 min
Client --> Livreur: suivre livreur

Livreur -> Commande: valider la livraison

end
@enduml