@startuml Client


Class Client {
    - prénom : string
    - nom : string
    - addresse : string
    - telephone : string
    - email : string
    - motDePasse : string
    
    + inscription()
    + seConnecter()
    + CommanderRepas()
    + SuivreCommande()
    + TelechargerFacture()
}

@enduml

