@startuml Order
' syntaxe qui permet d'inclure une classe  
!include Client.puml
!include Plat.puml
!include Paiement.puml
!include Livreur.puml
!include Facture.puml
!include CommandeManager.puml
!include LivreurManager.puml
!include Chef.puml
!include Dessert.puml


Class Commande {
    - numeroDeCommande : int

    + TelechargerCommande()
}

Chef "1"--* Plat: creer >
Chef "1"--* Dessert: creer >
Client "1"--* Commande: commande >
Commande *--* Plat: avoir <>
Commande "1"--"1" Facture 
Commande *--* Dessert: avoir <>
Commande "1"-"1" Paiement
Commande *--"1" Livreur: livre >
LivreurManager *-* Plat
LivreurManager <-- Commande: exec
LivreurManager <-- Livreur: sync
CommandeManager -- Paiement: creer >
CommandeManager -- Commande: creer >
CommandeManager -- Facture: creer >


@enduml


