@startuml Order
' syntaxe qui permet d'inclure une classe  
!include Client.puml
!include Repas.puml
!include Paiement.puml
!include Livreur.puml
!include Facture.puml
!include CommandeManager.puml
!include LivreurManager.puml
!include Chef.puml


Class Commande {
    - numeroDeCommande : int
    - dateDeCommande : DateTime
    - statutDeCommande : string
    
    + TelechargerCommande()
}

Sale *--"1" Chef: creer <
Sucre *--"1" Chef: creer <
Commande *--"1" Client: commande >
Commande *--* Repas: avoir <>
Commande "1"--"1" Facture 
Paiement "1"-"1" Commande
Commande *--"1" Livreur: livre >
Livreur *-* Repas: avoir <>
LivreurManager <-- Commande: exec
LivreurManager --> Livreur: sync
Paiement -- CommandeManager: creer <
CommandeManager -- Commande: creer >
CommandeManager -- Facture: creer >


@enduml


