@startuml CommandeManager

Class CommandeManager {

    + creerCommande(array plats, Client client)
    + creerListeCommandeDuJour(Commande commande)
    + payOrder(Commande commande)
    + createBill(Commande commande)
    
    }

@enduml