@startuml CommandeManager

Class CommandeManager {

    + creerCommande(array repas, Client client)
    + creerListeCommandeDuJour(Commande commande)
    + payerCommande(Commande commande)
    + creerFacture(Commande commande)
    
    }

@enduml