@startuml EquipeExpressFood

Class EquipeExpressFood {
    - email : string
    - motDePasse : string
    - roles: array
    
    + seConnecter()
    + ajouteSaleEtSucre()
}

@enduml



