@startuml EquipeExpressFood

Class EquipeExpressFood {
    - prénom : string
    - nom : string
    - motDePasse : string
    - roles: json
    
    + seConnecter()
    + ajouteSaleEtSucre()
}

@enduml



