@startuml LivreurManager

Class LivreurManager {
    - Livreurs : array

    + CalculerStockPlat(Plat plat)
    + trouverLivreur(Commande commande)
    + DemmarerLivraison(Commande commande)
}

@enduml