@startuml LivreurManager

Class LivreurManager {
    - Livreurs : array

    + CalculerStockRepas(Repas repas)
    + trouverLivreur(Commande commande)
    + DemmarerLivraison(Commande commande)
}

@enduml