@startuml Livreur

Class Livreur {
    - prénom : string
    - telephone : string
    - disponibilite : bool
    - email : string
    - motDePasse : string
    - longitude : int
    - latitude : int
    - repas : array

    + seConnecter()
    + calculerPosition()
    + LivrerCommande()
}

@enduml



