@startuml Order
' syntaxe qui permet d'inclure une classe  
!include Customer.puml
!include Meal.puml
!include Payment.puml
!include DeliveryMan.puml
!include Bill.puml
!include OrderManager.puml
!include BillManager.puml

Class Order {
    - numberOfOrder : int

    + Dowload()
    + addOrder() : int
}

Customer "1"--* Order
Order *--* Meal: have <>
Order -- Bill : create >
Order "1"-"1" Payment
Order "1"--* BillManager: trigger >
OrderManager -- Payment: create >
OrderManager -- Order: create >
BillManager -- Bill: create >

@enduml


