@startuml Plat

Class Plat {
    - nom : string
    - type : string
    - nature : string
    - ingredients : array
    - prix : int
    - stock : int
    - disponibilité : bool

    + calculerStock() : int
}

@enduml


