@startuml Repas

!include Sale.puml
!include Sucre.puml


Class Repas {
    - nom : string
    - type : string
    - nature : string
    - ingredients : array
    - prix : int
    - quantité : int
    - stock : int
    - disponibilité : bool

    + calculerStock() : int
}

Repas <|-- Sale: extends
Repas <|-- Sucre: extends

@enduml


