@startuml Repas

!include Sale.puml
!include Sucre.puml


abstract Class  Repas {
    - nom : string
    - type : string
    - nature : string
    - ingredients : array
    - prix : int
    - stock : int

    + calculerStock() : int
    +enStock() : bool
}

Repas <|-- Sale: extends
Repas <|-- Sucre: extends

@enduml


